### ISSUE TITLE
DLL load failed while importing pysoem

### ISSUE THREAD

**Issue by tomhira** [bnjmnp/pysoem#110]
Hi,
I recently switched PC to Windows 10 Pro.
and installed Python 3.11.4 and pysoem 1.1.3.
and I got this error.
import pysoem
ImportError: DLL load failed while importing pysoem

does someone had same experience, and inform me how to solve it?

**Comment by datviNasser** [comment]
Had same issue with Python 3.7.0 and pysoem 1.1.3:
Could solve it with an installation of npcap driver https://npcap.com/#download

**Comment by tomhira** [comment]
Hello datviNasser.
Thanks for help! It happened in the process of installing Wireshark, winPcap was not installed.
Error went away.
Best regards, Tom
