### ISSUE TITLE
Ethercat Ring Topology

### ISSUE THREAD

**Issue by Michaelicious** [bnjmnp/pysoem#124]
Is it possible to use 2 network interfaces for the same ecat network to create ring topology ?

**Comment by bnjmnp** [comment]
Recently I added a second optional parameter called `ifname_red` to the [`Master.open()`](https://pysoem.readthedocs.io/en/latest/master.html#pysoem.Master.open) function, this is used for the redundancy port, maybe this is exactly what you want.

Under the hood pyseom just uses the SOEM's `ecx_init_redundant()` if a second port is given. Whereas if only one port is given it uses standard `ecx_init()` function.

I just realized that the context managers `open()` function does not allow the seconde port, I'll add this soon.
