### ISSUE TITLE
Returning PDO frame late (Windows)

### ISSUE THREAD

**Issue by andre-comet** [bnjmnp/pysoem#130]
Probably this is no issue of pysoem itself, but I occasionally see a case where the pdo frame coming from the Ecat Subdevice is seen late by pysoem running on Windows. I have a simple network for testing, with only one device connected to pysoem.
The error appears as an EC_NOFRAME error (workingcounter returns as -1), because the frame from the sub device is not seen returning during the pdo timeout time (here 10ms).
In this wireshark grabs, on the right side, are the packets seen by pysoem. It seems that the sub device does not return the pdo frame in time, causing my pysoem implementation to send a BRD frame after pdo timeout (10ms).
However, if we look at the frames on the left side, which are captured by a second PC using a Beckhoff ET2000 sniffer, we can see that the frame was sent by the sub device immediately (wireshark shows delay since last packet as 0.000000s)
![image](https://github.com/bnjmnp/pysoem/assets/117835572/ae13c13c-6933-42d8-9173-07140bd9526b)

So the issue seems to happen somewhere between the NIC and windows application layer. Heightening the timeout to higher values does not help.
Is there anything I am missing here, or is there some need to optimize the network performance on a windows machine somehow? Or is it just not possible and we should use linux, or a proper realtime system?

**Comment by bnjmnp** [comment]
I've also seen occasional working counter errors on Windows but did not spend too much time debugging this. Maybe disabling network services not needed in the adapter settings can give some improvements.
For functional testing of Subdevices the working counter errors are not too big of a deal. But depending on your goals it might make sense to switch to pure SOEM and a proper real time system, right.

**Comment by andre-comet** [comment]
Yes the wkc errors are not often, but they make my tests flaky. I worked around this now by repeating tests that failed once.

disabling network services seemed to help at first but after a while of testing I could not see a correlation between disabling services and the commonness of the error. In the end it seemed just random. 
However, there seems to be a dependency of NIC model: While all I tested with were Intel models, they were not all the exact same type and on some, the error occurs much more frequent.

**Comment by GullinBustin** [comment]
@andre-comet I have exactly the same problem. Did you find any solution other than retrying the tests that fail?

**Comment by andre-comet** [comment]
Yes, I solved it _kind of_. At least for me, but the method is not "scientifically proven". The following list of settings worked for my adapter, and I have not seen the issue again since.
The procedure is loosely taken from the page [here](https://learn.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-performance-tuning-nics#bkmk_resources)

1.	Disable all services, except the Npcap driver and the QoS-Packet-Planner
 ![Image](https://github.com/user-attachments/assets/998338a6-0ece-40e0-8375-80865e3a6094)

2.	Click Configure, go to Advanced tab
 ![Image](https://github.com/user-attachments/assets/41a9168d-77d2-4b7d-99a6-2a2437ea54b9)

3.	Disable Flow Control
 ![Image](https://github.com/user-attachments/assets/36f6bc78-3661-41e9-b534-dfa8e55ca6a5)

4.	Disable Interrupt Moderation
![Image](https://github.com/user-attachments/assets/414a7b0e-96ff-44d8-a9b2-d62461c8a20f)
![Image](https://github.com/user-attachments/assets/860981d3-ad21-4d34-99a4-473f5aec70d9)

5.	Set Packet Priority & VLAN setting to Packet Priority Enabled
 ![Image](https://github.com/user-attachments/assets/e386d2f8-4796-458b-bf8b-d2c7d78d53c7)

6.	Enable all "Offload" options (they probably they are already enabled)
![Image](https://github.com/user-attachments/assets/c2b463c3-2c29-4159-8fe0-1b2a721f31d4)
 
If this does not help, refer to other options described here:
https://learn.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-performance-tuning-nics#bkmk_resources
