### ISSUE TITLE
read and write PDOS question

### ISSUE THREAD

**Issue by GoesWithoutSaying** [bnjmnp/pysoem#136]
i have read the basic.py and minimal.py. based on my coding level, i'm still confusing, hers is some question hope someone can help
1.for master.config_map() , slave.input and slave.output are the pdo data that mapped?
2.for master.send_processdata() and master.receive_processdata(), is slave.input and slave.output are the data that sending and receiving?
3. to write a PDO mapping, is it correct that using SDO?

**Comment by bnjmnp** [comment]
I think you got it now and we can close this issue?
