### ISSUE TITLE
pysoem on windows 10 problem - will appreciate help

### ISSUE THREAD

**Issue by NoamGraetz2** [bnjmnp/pysoem#14]
i am trying to use pysoem to emulate a master ethercat controller, but keep banging into a wall.

when i am trying to do pysoem.Master().open(name)   i keep getting
"interface {24D8A70B-00A0-4643-81DE-C1D2DF72396D} could not open with pcap"
message, no matter which interface i am trying to use

this is for all the interfaces detected by pysoem.find_adapters()

also, i have installed win10pcap and wireshark, and they can access any interface 

will appreciate any help

thanks

Noam

**Comment by NoamGraetz2** [comment]
well, after some deep diving, i think i have found the problem.
you should use npcap and not win10pcap...

**Comment by Vimes01** [comment]
I have the same problem (Windows 10, could not open with pcap, pysoem.find_adapters() finds ID, Wireshark works and can access interface), although I have installed npcap 1.50. Any suggestions?

**Comment by Vimes01** [comment]
In my case I needet to input ID in this format: '\\Device\\NPF_{A36B0DE6-FA8F-4113-AC4F-EEFF9E02CEC3}'

**Comment by msevnctkn** [comment]
have you solved the problem?

**Comment by agwidarsito** [comment]
Weird, on Win 11 we had to do this:

'\Device\\NPF_{A36B0DE6-FA8F-4113-AC4F-EEFF9E02CEC3}'

**Comment by tomhira** [comment]
Hello,
I have same problem except I am using Realtek USB GbE Family Controller.
I am using the notation: \Device\NPF_{7A0F6319-EC6D-4EF5-ADC5-52F691B8F63D}
with Winpcap installed.

could not open interface \Device\NPF_{7A0F6319-EC6D-4EF5-ADC5-52F691B8F63D}
  File "C:\basic_example.py", line 426, in run
    self._master.open(self._ifname)
  File "C:\basic_example.py", line 564, in <module>
    BasicExample('\\Device\\NPF_{7A0F6319-EC6D-4EF5-ADC5-52F691B8F63D}').run()
ConnectionError: could not open interface \Device\NPF_{7A0F6319-EC6D-4EF5-ADC5-52F691B8F63D}

What can I do to solve this issue?

**Comment by tomhira** [comment]
Hello, it seems the ncap is not properly installed with Windows 10 by selecting the option
Install Npcap in WinPcap API-compatible Mode (WinPcap will be uninstalled)

**Comment by BorisKomarov** [comment]
Also you can try this 
master.open(r'\Device\NPF_{B520D7ED-4AC0-48F9-9574-09C0696C3DA4}')
my mistake is that I didn't put "r" in front of the quotes with the interface name to read the slashes correctly
