### ISSUE TITLE
use named logger instead of root logger.

### ISSUE THREAD

**Issue by LukasBec** [bnjmnp/pysoem#39]
Using the root logger is inflexible. 
For example, it is not possible to set the Log Level or a specific handler only for pysoem.

It would be more convenient to use a named logger instead as suggested in
https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial

**Comment by bnjmnp** [comment]
Thank you very much for your suggestion and the PR, it is good to have this fixed.
For now I just merge this in the master branch but will update the package on PyPI later.
