### ISSUE TITLE
Contributing, communicating

### ISSUE THREAD

**Issue by Kamforka** [bnjmnp/pysoem#4]
Hey there,

First of all I have to say that I really like this ported version of `soem` and I would like to discuss ways of contributing and also sharing ideas in the future.

Do you have any official channel like `slack` or `gitter` where we could get together and communicate with each other?

**Comment by bnjmnp** [comment]
I've created a room on Gitter: [gitter.im/pysoem/pysoem](https://gitter.im/pysoem/pysoem)
