### ISSUE TITLE
Setup method for the package is looking like to become deprecated

### ISSUE THREAD

**Issue by rako233** [bnjmnp/pysoem#51]
As written in the topic, it's looking like the setup method is going to be deprecated with Python 3.12.

**Comment by bnjmnp** [comment]
Hi. Thank you for the hint. It is good to know that in advance.

I already have plans to rework my build/publication process using GitHub Actions and [cibuildwheel](https://github.com/pypa/cibuildwheel). When doing this I will check out the new way of crafting Python packages.

Do you have a link at hand were one can read what the setup method is replaced with?

**Comment by rako233** [comment]
Sorry, Idk. I just noted it when using pysoem
