### ISSUE TITLE
Help wanted, incorrect wkc at first boot?

### ISSUE THREAD

**Issue by tom9672** [bnjmnp/pysoem#68]
I use a raspberry pi and a servo only with DC mode.

At the first time I boot the raspberry pi, the PDO checking thread will show incorrect wkc and servo enable failed. The code #66.

Still not find out what makes the error. Thanks in advance if could give me some suggestions.

**Comment by GARBAGE-WALL-E** [comment]
Hi @tom9672 

Similar behavior in some other AC servo drives as well. It has something to do with initial buffer, may be something to do with previous PDO data in buffer. Haven't tried to figure out so far.

However following is a crude method to get past error, Keep reading any known SDO until the read value is what it should and then continue with your code.  

>I am working on something similar, can you please share your full code (along with PDO mapping),Also It would be really helpful if you could share your ESI file, datasheet of the device.

Just FYI :   0x6081 and  0x60FF, you mapped both to 0x1600, 0x4 
  0x6081 is Profile Velocity and 0x60FF is Target velocity, 
 
Following code
```
import pysoem
import struct
import ctypes
import time
master = pysoem.Master()

master.open('\\Device\\NPF_{23FFFBFE-C8A4-4C57-8FF3-65AD208FA513}')
cntr =0
if master.config_init() > 0:
  for device in master.slaves:
    while True:
        print(f'Found Device {device.name}')
        cntr += 1
        print(int.from_bytes(device.sdo_read(0x1000, 0), byteorder='little', signed=False))
        if(cntr>=10):
          break

    print(device.sdo_read(0x1008, 0).decode('utf-8'))
    time.sleep(2)
    print(device.sdo_read(0x1009, 0).decode('utf-8'))
    time.sleep(2)
    print(int.from_bytes(device.sdo_read(0x2000, 1), byteorder='little', signed=False))
    print(device.state)
    


else:
  print('no device found')
master.close()
```

Results In Following

```
Found Device ServoDrive
351267461655569700895372181450682466376049778813734863487462279337845239273165520922241740486030646924676196927358282962587707548366326808536007485987724478265681078915808808022441955598210013964578550720194750307566271409112063817807121816825033438144191109487668687985626909518714082685256861626266127292077831574311139744390302673632732786578723858581452364333088091934298110429529438403788166288410121465991065193259065061116566537619857172830022240542625739880345588283939871053739683097581768229956874699132209664209447334997867329132868932157228285929726310491026793927016037065709340026034481184043433992
Found Device ServoDrive
131474
Found Device ServoDrive
131474
Found Device ServoDrive
131474
Found Device ServoDrive
131474
DS100E-40
V1.0
17
1
```

Initially sdo_read() provides some garbage value regardless of what you ask,
