### ISSUE TITLE
Can not control Velocity in CSP Mode

### ISSUE THREAD

**Issue by GARBAGE-WALL-E** [bnjmnp/pysoem#84]
Edit : Will update with the working code soon.

**Comment by tom9672** [comment]
As the handbooks of ethercat servo drivers. The velocity of CSP mode is decided by servo driver itself (according to snchronization time and target position), user unable to set target velocity in this mode. If you need to let the motor runs at a targer velocity, I guess you'd better use PV or CSP mode.

**Comment by GARBAGE-WALL-E** [comment]
@tom9672 Thank you so much for the reply.
  I had doubts because, I went through the datasheet of several brand drives and one of them mentioned 70FF affects the CSP mode, also the TwinCat writes the velocity to 70FF in CSP.

  But anyways, I wrote the Acc and Dcc algorithms based on position and they are working fine, Also Increased the sync time and the directional motion issue is under the rug now.

> Yet it really bothers me, Why motion is smooth in one direction(+Ve) and not in other direction (-Ve)? You can notice it considerably as you lower down sync time.
  I have looked in to DemandedPosition value( at not very high refresh rate though) and it seems ok. Also I have tried different brand servo and the issue is still the same.
60B1, 60B2 are also set to zero.
Do you think, Does it have anything to do with underlying pysoem or soem?
Am I missing something? Any parameter?
